org.gradle.java.home=C:/Program Files/Java/eclipse_adoptium-21-amd64-windows.2
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.kotlin.dsl.allWarningsAsErrors=true
kotlin.jvm.target.validation.mode=IGNORE
kotlin.incremental=false

kotlin_for_forge_version = 5.10.0